ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE public.workers ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
